# Generated by Django 2.1 on 2018-10-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='下書き'),
        ),
    ]
